### ISSUE TITLE
Suppose 2^n 4K size maxKvValue

### ISSUE THREAD

**Issue by qizhou** [ethstorage/storage-contracts#1]
Currently maxKvValue is 4KB, which equals the chunk size 4KB.  In the future, we plan to support maxKvValue = 2^n 4KB.  For example, in Dankshardking, the data size is 128KB per BLOB; thus, using maxKvValue = 128KB may be a better storing option.

However, directly using maxKvValue (and its commitment) in proof of random access may be inefficient: if every challenge size is 128KB, then 16 random-position challenges will have the proof size = 128KB * 16 = 2MB!

Instead, the proof of random access should still use chunk size 4KB, and when an inclusion proof of a 4KB chunk within a 128KB value is needed, we could generate additional proof to show that the 4KB is in a 128KB value.  This will reduce the proof size of 16 random challenges from 2MB to 4KB * 16 + 5 (tree depth) * 32 (hash size) * 16 (# of challenges) = 66.5 KB.

**Comment by LiuJiazheng** [comment]
The feature has been merged. Hereby close it
