### ISSUE TITLE
Questions in contract DecentralizedKV.sol

### ISSUE THREAD

**Issue by LiuJiazheng** [ethstorage/storage-contracts#2]
While reading this contract, I come up with some questions. Hereby I list:
1. `function put(bytes32 key, bytes memory data) public payable`
https://github.com/ethstorage/storage-contracts/blob/28f3834d244dd6464dde5b66bab1db8aa935d62c/contracts/DecentralizedKV.sol#L111
Transaction flow: Ideally, if caller calls the `put` function without any existing skey, that means this skey is first time to be used. Once IStorageManager putRaw returns successfully, we shall subtract money from msg.sender (caller, the one who calls this method to store data), and compensate the data host (where in this case, is IStorageManager.address), by upfrontPayment, as a permanent rental fee.
Without a global ledger(A hash map in implementation), how can we reflect the transaction?

2. `function removeTo(bytes32 key, address to) public`
https://github.com/ethstorage/storage-contracts/blob/28f3834d244dd6464dde5b66bab1db8aa935d62c/contracts/DecentralizedKV.sol#L178
Again, transaction flow: the payable(to) should be refunded money, just as code shows, but the data host shall be subtracted such amount of money as well. To me the code seems losing a half.
Is there any chance to face insufficient fund to conduct refund? Which part tracks the money down?

3. `function removeTo(bytes32 key, address to) public`
https://github.com/ethstorage/storage-contracts/blob/28f3834d244dd6464dde5b66bab1db8aa935d62c/contracts/DecentralizedKV.sol#L157
Safety concern: it is public, that means an attcker can serve as caller as well. We know `keccak256` is collision-proof and since different msg.sender is different address, skey can never be same. But key can be twisted so there remains chance for attackers to wipe others' data out, no?

**Comment by qizhou** [comment]
> 1. Without a global ledger(A hash map in implementation), how can we reflect the transaction?

The blockchain world state itself is a global ledger, and the default storage (via SSTORE/SLOAD) is a key-value mapping (key and value are 32 bytes)



> * Is there any chance to face insufficient fund to conduct refund? Which part tracks the money down?

The function will return the rest fee paid by the users, i.e., upfrontPayment() will return the payment/refund value from time now to infinity.



> 3\. Safety concern: it is public, that means an attcker can serve as caller as well. We know `keccak256` is collision-proof and since different msg.sender is different address, skey can never be same. But key can be twisted so there remains chance for attackers to wipe others' data out, no?

keccak256() is a collision-free cryptographic hash, which means that even `key` can be arbitrary, it is impossible to find a `key` that collides with another address's `skey`.

**Comment by LiuJiazheng** [comment]
The missing part of myself is, I forgot the msg.value carries the eth of which caller needs to pay. That part, as a part of call stack, will accompany with calling of particular method, then vanishes, symbolizing a transition from contract caller to block per se.

After knowing this part. The puzzle is easier to solve. Block itself, containing a world state, serving sorts of ledger. Take function `put` as an example. When callers use this function to register a skey at first time, they must carry value no less than upfrontPatment() as storage fee. After the successful execution of put method in EVM, the world state would transit, block holds that fee. Since msg.value comes from caller's wallet, the fee has been paid already.
